/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package package1;

import java.awt.Toolkit;
import javax.swing.JOptionPane;
import java.awt.event.WindowEvent;

/**
 *
 * @author user
 */

public class Frame1 extends javax.swing.JFrame {
    
    String gender;
    String pendamping;
    String bulan1, bulan2;
    private String nama1, tempat1, alamat, kelurahan, kecamatan, kota, universitas;
    private String nama2, tempat2, pekerjaan;
    
    //setter
    public void setNama1(String newNama1) {
        this.nama1 = newNama1;
    }
    
    public void setNama2(String newNama2){
        this.nama2 = newNama2;
    }
    
    public void setTempat2(String newTempat2){
        this.tempat2 = newTempat2;
    }
    
    public void setPekerjaan(String newPekerjaan){
        this.pekerjaan = newPekerjaan;
    }
    
    public void setTempat1(String newTempat1){
        this.tempat1 = newTempat1;
    }
    
    public void setAlamat(String newAlamat){
        this.alamat = newAlamat;
    }
    
    public void setKelurahan(String newKelurahan){
        this.kelurahan = newKelurahan;
    }
    
    public void setKecamatan(String newKecamatan){
        this.kecamatan = newKecamatan;
    }
    
    public void setKota(String newKota){
        this.kota = newKota;
    }
    
    public void setUniversitas(String newUniversitas){
        this.universitas = newUniversitas;
    }
    
    //getter
    public String getNama1() {
        return this.nama1;
    }

    public String getNama2() {
        return this.nama2;
    }

    public String getTempat2() {
        return this.tempat2;
    }

    public String getPekerjaan() {
        return this.pekerjaan;
    }

    public String getTempat1() {
        return this.tempat1;
    }

    public String getAlamat() {
        return this.alamat;
    }

    public String getKelurahan() {
        return this.kelurahan;
    }

    public String getKecamatan() {
        return this.kecamatan;
    }

    public String getKota() {
        return this.kota;
    }

    public String getUniversitas() {
        return this.universitas;
    }

   

    /**
     * Creates new form Frame1
     */
    public Frame1() {
        initComponents();
        Combo_Fak.setSelectedItem(null);
        Combo_Bulan1.setSelectedItem(null);
        Combo_Bulan2.setSelectedItem(null);
        Combo_Pendapatan.setSelectedItem(null);
        this.setDefaultCloseOperation(Frame1.EXIT_ON_CLOSE);
    }
    
    //fungsi pengecekan
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Txt_Nama1 = new javax.swing.JTextField();
        Combo_Tanggal1 = new javax.swing.JComboBox<>();
        rb_Laki = new javax.swing.JRadioButton();
        Txt_Tempat1 = new javax.swing.JTextField();
        rb_Perempuan = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        Txt_Tahun1 = new javax.swing.JTextField();
        Txt_Univ = new javax.swing.JTextField();
        Combo_Fak = new javax.swing.JComboBox<>();
        Combo_Jur = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Txt_Alamat1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Combo_Bulan1 = new javax.swing.JComboBox<>();
        Txt_Kota1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Txt_Kelurahan1 = new javax.swing.JTextField();
        Txt_KP = new javax.swing.JTextField();
        Txt_Kecamatan1 = new javax.swing.JTextField();
        bt_Next1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        rb_Ortu = new javax.swing.JRadioButton();
        rb_Wali = new javax.swing.JRadioButton();
        Txt_Nama2 = new javax.swing.JTextField();
        Txt_Tempat2 = new javax.swing.JTextField();
        Txt_Pekerjaan = new javax.swing.JTextField();
        Combo_Bulan2 = new javax.swing.JComboBox<>();
        Combo_Tanggal2 = new javax.swing.JComboBox<>();
        Txt_Tahun2 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        Txt_Biaya = new javax.swing.JTextField();
        Txt_Tanggungan = new javax.swing.JTextField();
        Combo_Pendapatan = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data Pendaftar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        Combo_Tanggal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Combo_Tanggal1ActionPerformed(evt);
            }
        });

        buttonGroup2.add(rb_Laki);
        rb_Laki.setText("Laki-laki");
        rb_Laki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_LakiActionPerformed(evt);
            }
        });

        Txt_Tempat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_Tempat1ActionPerformed(evt);
            }
        });

        buttonGroup2.add(rb_Perempuan);
        rb_Perempuan.setText("Perempuan");
        rb_Perempuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_PerempuanActionPerformed(evt);
            }
        });

        jLabel15.setText("Universitas");

        Txt_Tahun1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_Tahun1ActionPerformed(evt);
            }
        });
        Txt_Tahun1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Txt_Tahun1KeyTyped(evt);
            }
        });

        Combo_Fak.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fakultas Teknik", "Fakultas Psikologi", "Fakultas Sains dan Matematika", "Fakultas Peternakan dan Pertanian", " " }));
        Combo_Fak.setName(""); // NOI18N
        Combo_Fak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Combo_FakActionPerformed(evt);
            }
        });

        jLabel12.setText("Jenis Kelamin");

        jLabel2.setText("Nama");

        jLabel3.setText("Tempat, Tanggal Lahir");

        jLabel4.setText("Fakultas");

        jLabel13.setText("Alamat Rumah");

        jLabel14.setText("Kabupaten / Kota");

        jLabel5.setText("Jurusan");

        Combo_Bulan1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        Combo_Bulan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Combo_Bulan1ActionPerformed(evt);
            }
        });

        jLabel10.setText("Kelurahan");

        jLabel11.setText("Kecamatan");

        jLabel16.setText("Kode Pos");

        Txt_KP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Txt_KPKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Txt_Kecamatan1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Txt_Kelurahan1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Txt_Alamat1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rb_Laki)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rb_Perempuan))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(Txt_Tempat1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Combo_Bulan1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Combo_Tanggal1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Txt_Tahun1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(Txt_Nama1, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Txt_Kota1, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Txt_KP, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Txt_Univ, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Combo_Fak, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Combo_Jur, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Txt_Nama1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Txt_Tempat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Combo_Bulan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Combo_Tanggal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt_Tahun1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(rb_Laki)
                    .addComponent(rb_Perempuan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(Txt_Alamat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(Txt_Kelurahan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(Txt_Kecamatan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(Txt_Kota1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(Txt_KP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(Txt_Univ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Combo_Fak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Combo_Jur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        bt_Next1.setText("Berikutnya");
        bt_Next1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_Next1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Formulir Pendaftaran Beasiswa");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data Orang Tua / Wali", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        jLabel1.setText("Nama");

        jLabel7.setText("Tempat, Tanggal Lahir");

        jLabel8.setText("Pekerjaan");

        jLabel17.setText("Orang tua / Wali");

        buttonGroup1.add(rb_Ortu);
        rb_Ortu.setText("Orang tua");
        rb_Ortu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_OrtuActionPerformed(evt);
            }
        });

        buttonGroup1.add(rb_Wali);
        rb_Wali.setText("Wali");
        rb_Wali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_WaliActionPerformed(evt);
            }
        });

        Combo_Bulan2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        Combo_Bulan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Combo_Bulan2ActionPerformed(evt);
            }
        });

        Txt_Tahun2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Txt_Tahun2KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(rb_Ortu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rb_Wali)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Txt_Nama2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(Txt_Tempat2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Combo_Bulan2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Combo_Tanggal2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Txt_Tahun2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Txt_Pekerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(rb_Wali)
                    .addComponent(rb_Ortu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Txt_Nama2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Txt_Tempat2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Combo_Bulan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Combo_Tanggal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt_Tahun2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Txt_Pekerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informasi Tambahan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        jLabel9.setText("Pendapatan Orang Tua / Wali");

        jLabel18.setText("Biaya per-semester");

        jLabel19.setText("Jumlah Tanggungan");

        Txt_Tanggungan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Txt_TanggunganKeyTyped(evt);
            }
        });

        Combo_Pendapatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<1 jt per bulan", "1-3 jt per bulan", "3-4 jt per bulan", ">4 jt per bulan" }));
        Combo_Pendapatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Combo_PendapatanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Txt_Tanggungan)
                    .addComponent(Combo_Pendapatan, javax.swing.GroupLayout.Alignment.LEADING, 0, 261, Short.MAX_VALUE)
                    .addComponent(Txt_Biaya, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(Combo_Pendapatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(Txt_Biaya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(Txt_Tanggungan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bt_Next1))
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_Next1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_Next1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_Next1ActionPerformed
        // TODO add your handling code here:
        this.toBack();
        Frame2 pi = new Frame2();
        //set
        setNama1(Txt_Nama1.getText());
        setNama2(Txt_Nama2.getText());
        setTempat1(Txt_Tempat1.getText());
        setTempat2(Txt_Tempat2.getText());
        setAlamat(Txt_Alamat1.getText());
        setKelurahan(Txt_Kelurahan1.getText());
        setKecamatan(Txt_Kecamatan1.getText());
        setKota(Txt_Kota1.getText());
        setUniversitas(Txt_Univ.getText());
        setPekerjaan(Txt_Pekerjaan.getText());
        

        Frame2.TxtA_Data.setText(
                "Data Pendaftar" + "\n" +
                "Nama : " + getNama1() + "\n" +
                "Tempat, Tanggal Lahir : " + getTempat1() + ", " + Combo_Tanggal1.getSelectedItem() + " " + String.valueOf(bulan1) + " " + Txt_Tahun1.getText() + "\n" +
                "Jenis Kelamin : " + String.valueOf(gender) + "\n" +
                "Alamat : " + getAlamat() + ", " + getKelurahan() + ", " + getKecamatan() + ", " + getKota() + ", " + Txt_KP.getText() + "\n" +
                "Universitas : " + getUniversitas() + "\n" +
                "Fakultas : " + Combo_Fak.getSelectedItem() + "\n" +
                "Jurusan : " + Combo_Jur.getSelectedItem() + "\n" + 
                "\n" + 
                "Data Orang Tua / Wali" + "\n" +
                "Data milik : " + String.valueOf(pendamping) + "\n" +
                "Nama : " + getNama2() + "\n" +
                "Tempat, Tanggal Lahir : " + getTempat2() + ", " + Combo_Tanggal2.getSelectedItem() + " " + String.valueOf(bulan2) + " " + Txt_Tahun2.getText() + "\n" +
                "Pekerjaan : " + getPekerjaan() + "\n" +
                "\n" +
                "Informasi Tambahan" + "\n" +
                "Pendapatan Orang Tua / Wali : " + Combo_Pendapatan.getSelectedItem() + "\n" +
                "Biaya Kuliah per-semester : " + "Rp. " + Txt_Biaya.getText() + "\n" + 
                "Jumlah Tanggungan : " + Txt_Tanggungan.getText() + "\n");

        pi.setVisible(true);
        pi.toFront();
    }//GEN-LAST:event_bt_Next1ActionPerformed

    private void Combo_FakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Combo_FakActionPerformed
        // TODO add your handling code here:
        try{
            if(Combo_Fak.getSelectedItem().equals("Fakultas Teknik")){
                Combo_Jur.removeAllItems();
                Combo_Jur.setSelectedItem(null);
                Combo_Jur.addItem("Teknik Komputer");
                Combo_Jur.addItem("Teknik Perkapalan");
                Combo_Jur.addItem("Teknik Mesin");
                Combo_Jur.addItem("Teknik Elektro");
                Combo_Jur.addItem("Teknik Industri");
                Combo_Jur.addItem("Teknik Sipil");
            }
            else if(Combo_Fak.getSelectedItem().equals("Fakultas Psikologi")){
                Combo_Jur.removeAllItems();
                Combo_Jur.setSelectedItem(null);
                Combo_Jur.addItem("Psikologi Umum & Eksperimen");
                Combo_Jur.addItem("Psikologi Perkembangan");
                Combo_Jur.addItem("Psikologi Peendidikan");
                Combo_Jur.addItem("Psikologi Sosial");
                Combo_Jur.addItem("Psikologi Klinis");
                Combo_Jur.addItem("Psikologi Industri & Organisasi");
            }
            else if(Combo_Fak.getSelectedItem().equals("Fakultas Psikologi")){
                Combo_Jur.removeAllItems();
                Combo_Jur.setSelectedItem(null);
                Combo_Jur.addItem("Psikologi Umum & Eksperimen");
                Combo_Jur.addItem("Psikologi Perkembangan");
                Combo_Jur.addItem("Psikologi Peendidikan");
                Combo_Jur.addItem("Psikologi Sosial");
                Combo_Jur.addItem("Psikologi Klinis");
                Combo_Jur.addItem("Psikologi Industri & Organisasi");
            }
            else if(Combo_Fak.getSelectedItem().equals("Fakultas Sains dan Matematika")){
                Combo_Jur.removeAllItems();
                Combo_Jur.setSelectedItem(null);
                Combo_Jur.addItem("Matematika");
                Combo_Jur.addItem("Biologi");
                Combo_Jur.addItem("Fisika");
                Combo_Jur.addItem("Kimia");
                Combo_Jur.addItem("Statistika");
                Combo_Jur.addItem("Informatika");
            }
            else if(Combo_Fak.getSelectedItem().equals("Fakultas Peternakan dan Pertanian")){
                Combo_Jur.removeAllItems();
                Combo_Jur.setSelectedItem(null);
                Combo_Jur.addItem("Teknologi Pangan");
                Combo_Jur.addItem("Agroekoteknologi");
                Combo_Jur.addItem("Agribisnis");
                Combo_Jur.addItem("Peternakan");
            }
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_Combo_FakActionPerformed

    private void Txt_Tempat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_Tempat1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_Tempat1ActionPerformed

    private void Combo_Tanggal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Combo_Tanggal1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_Combo_Tanggal1ActionPerformed

    private void Combo_Bulan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Combo_Bulan1ActionPerformed
        // TODO add your handling code here: 
        int t = 1;
        
        try{
            if(Combo_Bulan1.getSelectedItem().equals("1")){
                    Combo_Tanggal1.removeAllItems();
                    Combo_Tanggal1.setSelectedItem(null);
                    for( ; t<= 31; t++){
                        Combo_Tanggal1.addItem(String.valueOf(t));
                    }
                    bulan1 = "Januari";
            }
            else if(Combo_Bulan1.getSelectedItem().equals("2")){
                    Combo_Tanggal1.removeAllItems();
                    Combo_Tanggal1.setSelectedItem(null);
                    for( ; t<= 29; t++){
                        Combo_Tanggal1.addItem(String.valueOf(t));
                    }
                    bulan1 = "Februari";
            }
            else if(Combo_Bulan1.getSelectedItem().equals("3")){
                    Combo_Tanggal1.removeAllItems();
                    Combo_Tanggal1.setSelectedItem(null);
                    for( ; t<= 31; t++){
                        Combo_Tanggal1.addItem(String.valueOf(t));
                    }
                    bulan1 = "Maret";
            }
            else if(Combo_Bulan1.getSelectedItem().equals("4")){
                    Combo_Tanggal1.removeAllItems();
                    Combo_Tanggal1.setSelectedItem(null);
                    for( ; t<= 30; t++){
                        Combo_Tanggal1.addItem(String.valueOf(t));
                    }
                    bulan1 = "April";
            }
            else if(Combo_Bulan1.getSelectedItem().equals("5")){
                    Combo_Tanggal1.removeAllItems();
                    Combo_Tanggal1.setSelectedItem(null);
                    for( ; t<= 31; t++){
                        Combo_Tanggal1.addItem(String.valueOf(t));
                    }
                    bulan1 = "Mei";
            }
            else if(Combo_Bulan1.getSelectedItem().equals("6")){
                    Combo_Tanggal1.removeAllItems();
                    Combo_Tanggal1.setSelectedItem(null);
                    for( ; t<= 30; t++){
                        Combo_Tanggal1.addItem(String.valueOf(t));
                    }
                    bulan1 = "Juni";
            }
            else if(Combo_Bulan1.getSelectedItem().equals("7")){
                    Combo_Tanggal1.removeAllItems();
                    Combo_Tanggal1.setSelectedItem(null);
                    for( ; t<= 31; t++){
                        Combo_Tanggal1.addItem(String.valueOf(t));
                    }
                    bulan1 = "Juli";
            }
            else if(Combo_Bulan1.getSelectedItem().equals("8")){
                    Combo_Tanggal1.removeAllItems();
                    Combo_Tanggal1.setSelectedItem(null);
                    for( ; t<= 31; t++){
                        Combo_Tanggal1.addItem(String.valueOf(t));
                    }
                    bulan1 = "Agustus";
            }
            else if(Combo_Bulan1.getSelectedItem().equals("9")){
                    Combo_Tanggal1.removeAllItems();
                    Combo_Tanggal1.setSelectedItem(null);
                    for( ; t<= 30; t++){
                        Combo_Tanggal1.addItem(String.valueOf(t));
                    }
                    bulan1 = "September";
            }
            else if(Combo_Bulan1.getSelectedItem().equals("10")){
                    Combo_Tanggal1.removeAllItems();
                    Combo_Tanggal1.setSelectedItem(null);
                    for( ; t<= 31; t++){
                        Combo_Tanggal1.addItem(String.valueOf(t));
                    }
                    bulan1 = "Oktober";
            }
            else if(Combo_Bulan1.getSelectedItem().equals("11")){
                    Combo_Tanggal1.removeAllItems();
                    Combo_Tanggal1.setSelectedItem(null);
                    for( ; t<= 30; t++){
                        Combo_Tanggal1.addItem(String.valueOf(t));
                    }
                    bulan1 = "November";
            }
            else if(Combo_Bulan1.getSelectedItem().equals("12")){
                    Combo_Tanggal1.removeAllItems();
                    Combo_Tanggal1.setSelectedItem(null);
                    for( ; t<= 31; t++){
                        Combo_Tanggal1.addItem(String.valueOf(t));
                    }
                    bulan1 = "Desember";
            }
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_Combo_Bulan1ActionPerformed

    private void Combo_Bulan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Combo_Bulan2ActionPerformed
        // TODO add your handling code here:
        int t = 1;
        
        try{
            if(Combo_Bulan2.getSelectedItem().equals("1")){
                    Combo_Tanggal2.removeAllItems();
                    Combo_Tanggal2.setSelectedItem(null);
                    for( ; t<= 31; t++){
                        Combo_Tanggal2.addItem(String.valueOf(t));
                    }
                    bulan2 = "Januari";
            }
            else if(Combo_Bulan2.getSelectedItem().equals("2")){
                    Combo_Tanggal2.removeAllItems();
                    Combo_Tanggal2.setSelectedItem(null);
                    for( ; t<= 29; t++){
                        Combo_Tanggal2.addItem(String.valueOf(t));
                    }
                    bulan2 = "Februari";
            }
            else if(Combo_Bulan2.getSelectedItem().equals("3")){
                    Combo_Tanggal2.removeAllItems();
                    Combo_Tanggal2.setSelectedItem(null);
                    for( ; t<= 31; t++){
                        Combo_Tanggal2.addItem(String.valueOf(t));
                    }
                    bulan2 = "Maret";
            }
            else if(Combo_Bulan2.getSelectedItem().equals("4")){
                    Combo_Tanggal2.removeAllItems();
                    Combo_Tanggal2.setSelectedItem(null);
                    for( ; t<= 30; t++){
                        Combo_Tanggal2.addItem(String.valueOf(t));
                    }
                    bulan2 = "April";
            }
            else if(Combo_Bulan2.getSelectedItem().equals("5")){
                    Combo_Tanggal2.removeAllItems();
                    Combo_Tanggal2.setSelectedItem(null);
                    for( ; t<= 31; t++){
                        Combo_Tanggal2.addItem(String.valueOf(t));
                    }
                    bulan2 = "Mei";
            }
            else if(Combo_Bulan2.getSelectedItem().equals("6")){
                    Combo_Tanggal2.removeAllItems();
                    Combo_Tanggal2.setSelectedItem(null);
                    for( ; t<= 30; t++){
                        Combo_Tanggal2.addItem(String.valueOf(t));
                    }
                    bulan2 = "Juni";
            }
            else if(Combo_Bulan2.getSelectedItem().equals("7")){
                    Combo_Tanggal2.removeAllItems();
                    Combo_Tanggal2.setSelectedItem(null);
                    for( ; t<= 31; t++){
                        Combo_Tanggal2.addItem(String.valueOf(t));
                    }
                    bulan2 = "Juli";
            }
            else if(Combo_Bulan2.getSelectedItem().equals("8")){
                    Combo_Tanggal2.removeAllItems();
                    Combo_Tanggal2.setSelectedItem(null);
                    for( ; t<= 31; t++){
                        Combo_Tanggal2.addItem(String.valueOf(t));
                    }
                    bulan2 = "Agustus";
            }
            else if(Combo_Bulan2.getSelectedItem().equals("9")){
                    Combo_Tanggal2.removeAllItems();
                    Combo_Tanggal2.setSelectedItem(null);
                    for( ; t<= 30; t++){
                        Combo_Tanggal2.addItem(String.valueOf(t));
                    }
                    bulan2 = "September";
            }
            else if(Combo_Bulan2.getSelectedItem().equals("10")){
                    Combo_Tanggal2.removeAllItems();
                    Combo_Tanggal2.setSelectedItem(null);
                    for( ; t<= 31; t++){
                        Combo_Tanggal2.addItem(String.valueOf(t));
                    }
                    bulan2 = "Oktober";
            }
            else if(Combo_Bulan2.getSelectedItem().equals("11")){
                    Combo_Tanggal2.removeAllItems();
                    Combo_Tanggal2.setSelectedItem(null);
                    for( ; t<= 30; t++){
                        Combo_Tanggal2.addItem(String.valueOf(t));
                    }
                    bulan2 = "November";
            }
            else if(Combo_Bulan2.getSelectedItem().equals("12")){
                    Combo_Tanggal2.removeAllItems();
                    Combo_Tanggal2.setSelectedItem(null);
                    for( ; t<= 31; t++){
                        Combo_Tanggal2.addItem(String.valueOf(t));
                    }
                    bulan2 = "Desember";
            }
        }
        catch(Exception e){
            System.out.println(e);
        }


    }//GEN-LAST:event_Combo_Bulan2ActionPerformed

    private void rb_LakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_LakiActionPerformed
        // TODO add your handling code here:
        if (rb_Laki.isSelected()){
            gender = "Laki-laki";
        }
    }//GEN-LAST:event_rb_LakiActionPerformed

    private void rb_PerempuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_PerempuanActionPerformed
        // TODO add your handling code here:
        if (rb_Perempuan.isSelected()){
            gender = "Perempuan";
        }
    }//GEN-LAST:event_rb_PerempuanActionPerformed

    private void rb_OrtuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_OrtuActionPerformed
        // TODO add your handling code here:
        if (rb_Ortu.isSelected()){
            pendamping = "Orang Tua";
        }
    }//GEN-LAST:event_rb_OrtuActionPerformed

    private void rb_WaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_WaliActionPerformed
        // TODO add your handling code here:
        if (rb_Wali.isSelected()){
            pendamping = "Wali";
        }
    }//GEN-LAST:event_rb_WaliActionPerformed

    private void Combo_PendapatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Combo_PendapatanActionPerformed
        // TODO add your handling code here:
        try{
            
        }
        catch (Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_Combo_PendapatanActionPerformed

    private void Txt_KPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_KPKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        
        if(!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_Txt_KPKeyTyped

    private void Txt_Tahun1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_Tahun1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_Tahun1ActionPerformed

    private void Txt_Tahun1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_Tahun1KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        
        if(!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_Txt_Tahun1KeyTyped

    private void Txt_Tahun2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_Tahun2KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        
        if(!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_Txt_Tahun2KeyTyped

    private void Txt_TanggunganKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_TanggunganKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        
        if(!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_Txt_TanggunganKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox<String> Combo_Bulan1;
    public static javax.swing.JComboBox<String> Combo_Bulan2;
    private static javax.swing.JComboBox<String> Combo_Fak;
    public static javax.swing.JComboBox<String> Combo_Jur;
    private javax.swing.JComboBox<String> Combo_Pendapatan;
    public static javax.swing.JComboBox<String> Combo_Tanggal1;
    public static javax.swing.JComboBox<String> Combo_Tanggal2;
    public static javax.swing.JTextField Txt_Alamat1;
    private javax.swing.JTextField Txt_Biaya;
    public static javax.swing.JTextField Txt_KP;
    public static javax.swing.JTextField Txt_Kecamatan1;
    public static javax.swing.JTextField Txt_Kelurahan1;
    public static javax.swing.JTextField Txt_Kota1;
    public static javax.swing.JTextField Txt_Nama1;
    public static javax.swing.JTextField Txt_Nama2;
    public static javax.swing.JTextField Txt_Pekerjaan;
    public static javax.swing.JTextField Txt_Tahun1;
    public static javax.swing.JTextField Txt_Tahun2;
    private javax.swing.JTextField Txt_Tanggungan;
    public static javax.swing.JTextField Txt_Tempat1;
    public static javax.swing.JTextField Txt_Tempat2;
    public static javax.swing.JTextField Txt_Univ;
    private javax.swing.JButton bt_Next1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public static javax.swing.JRadioButton rb_Laki;
    public static javax.swing.JRadioButton rb_Ortu;
    private javax.swing.JRadioButton rb_Perempuan;
    public static javax.swing.JRadioButton rb_Wali;
    // End of variables declaration//GEN-END:variables
}
